images:
  - postgres:9.5
  - postgresci/postgres96-test

commands:
  - "echo 'Dogfooding :)'"
  - "bash test_suite_setup_script.sh"

postgres:
  database: postgres_ci
  username: tester
  password: Slonik